package cz.muni.fi.pv168.agentmanager.app.gui.involvement;

import cz.muni.fi.pv168.agentmanager.app.gui.AgentManagerMain;
import cz.muni.fi.pv168.agentmanager.app.gui.mission.MissionComboBoxModel;
import cz.muni.fi.pv168.agentmanager.app.gui.agent.AgentComboBoxModel;
import cz.muni.fi.pv168.agentmanager.app.workers.agent.AgentComboBoxWorker;
import cz.muni.fi.pv168.agentmanager.app.workers.mission.MissionComboBoxWorker;
import cz.muni.fi.pv168.gmiterkosys.AgentManager;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import cz.muni.fi.pv168.gmiterkosys.MissionManager;
import java.beans.PropertyChangeEvent;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Jaromir Sys
 */
public class InvolvementCreateDialog extends javax.swing.JDialog {

    /**
     * Creates new form InvolvementDialog
     *
     * @param parent
     * @param agentManager
     * @param missionManager
     */
    public InvolvementCreateDialog(java.awt.Frame parent, AgentManager agentManager, MissionManager missionManager) {
        super(parent, false);
        initComponents();
        involvementPanel1.addPropertyChangeListener("panelValid", (PropertyChangeEvent evt) -> {
            createInvolvementButton.setEnabled((Boolean) evt.getNewValue());
        });
        involvementPanel1.checkPanelValidity();

        AgentComboBoxModel agentComboBoxModel = new AgentComboBoxModel();
        MissionComboBoxModel missionComboBoxModel = new MissionComboBoxModel();

        involvementPanel1.getAgentComboBox().setModel(agentComboBoxModel);
        involvementPanel1.getMissionComboBox().setModel(missionComboBoxModel);

        //load data
        new AgentComboBoxWorker(agentManager, agentComboBoxModel).execute();
        new MissionComboBoxWorker(missionManager, missionComboBoxModel).execute();

        involvementPanel1.getAgentComboBox().getModel().addListDataListener(new ListDataListener() {

            @Override
            public void intervalAdded(ListDataEvent e) {
                involvementPanel1.getAgentComboBox().setSelectedItem(involvementPanel1.getAgentComboBox().getModel().getElementAt(0));
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
            }
        });

        involvementPanel1.getMissionComboBox().getModel().addListDataListener(new ListDataListener() {

            @Override
            public void intervalAdded(ListDataEvent e) {
                involvementPanel1.getMissionComboBox().setSelectedItem(involvementPanel1.getMissionComboBox().getModel().getElementAt(0));
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        involvementPanel = new javax.swing.JPanel();
        involvementPanel1 = new cz.muni.fi.pv168.agentmanager.app.gui.involvement.InvolvementPanel();
        actionPanel = new javax.swing.JPanel();
        createInvolvementButton = new javax.swing.JButton();
        cancelInvolvementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        involvementPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        involvementPanel.setLayout(new javax.swing.BoxLayout(involvementPanel, javax.swing.BoxLayout.PAGE_AXIS));
        involvementPanel.add(involvementPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        createInvolvementButton.setText(bundle.getString("action.create")); // NOI18N
        createInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(createInvolvementButton);

        cancelInvolvementButton.setText(bundle.getString("action.cancel")); // NOI18N
        cancelInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelInvolvementButton);

        involvementPanel.add(actionPanel);

        getContentPane().add(involvementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvolvementButtonActionPerformed
        Involvement involvement = new Involvement();
        involvement.setAgent(involvementPanel1.getInvolvementAgent());
        involvement.setMission(involvementPanel1.getInvolvementMission());
        involvement.setStart(involvementPanel1.getInvolvementStart());
        involvement.setEnd(involvementPanel1.getInvolvementEnd());

        getMainWindow().createInvolvement(involvement);
        close();
    }//GEN-LAST:event_createInvolvementButtonActionPerformed

    private void cancelInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInvolvementButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelInvolvementButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelInvolvementButton;
    private javax.swing.JButton createInvolvementButton;
    private javax.swing.JPanel involvementPanel;
    private cz.muni.fi.pv168.agentmanager.app.gui.involvement.InvolvementPanel involvementPanel1;
    // End of variables declaration//GEN-END:variables

    private AgentManagerMain getMainWindow() {
        return (AgentManagerMain) getParent();
    }

    private void close() {
        this.dispose();
    }
}
