package cz.muni.fi.pv168.agentmanager.app.gui.mission;

import cz.muni.fi.pv168.agentmanager.app.gui.AgentManagerMain;
import cz.muni.fi.pv168.agentmanager.app.gui.involvement.InvolvementTableModel;
import cz.muni.fi.pv168.agentmanager.app.workers.involvement.InvolvementByMissionTableModelWorker;
import cz.muni.fi.pv168.gmiterkosys.InvolvementManager;
import cz.muni.fi.pv168.gmiterkosys.Mission;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Jaromir Sys
 */
public class MissionDetailDialog extends javax.swing.JDialog {

    private Mission mission;

    public MissionDetailDialog(java.awt.Frame parent, Mission mission, InvolvementManager involvementManager) {
        super(parent, false);
        initComponents();
        missionPanel1.addPropertyChangeListener("panelValid", (PropertyChangeEvent evt) -> {
            updateMissionButton.setEnabled((Boolean) evt.getNewValue());
        });
        
        setMission(mission);

        //load data
        new InvolvementByMissionTableModelWorker(mission, involvementManager, ((InvolvementTableModel) involvementsTable.getModel())).execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        missionPanel = new javax.swing.JPanel();
        missionPanel1 = new cz.muni.fi.pv168.agentmanager.app.gui.mission.MissionPanel();
        actionPanel = new javax.swing.JPanel();
        updateMissionButton = new javax.swing.JButton();
        removeMissionButton = new javax.swing.JButton();
        cancelMissionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        involvementsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        missionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        missionPanel.setLayout(new javax.swing.BoxLayout(missionPanel, javax.swing.BoxLayout.Y_AXIS));
        missionPanel.add(missionPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        updateMissionButton.setText(bundle.getString("action.update")); // NOI18N
        updateMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMissionButtonActionPerformed(evt);
            }
        });
        actionPanel.add(updateMissionButton);

        removeMissionButton.setText(bundle.getString("action.remove")); // NOI18N
        removeMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMissionButtonActionPerformed(evt);
            }
        });
        actionPanel.add(removeMissionButton);

        cancelMissionButton.setText(bundle.getString("action.cancel")); // NOI18N
        cancelMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMissionButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelMissionButton);

        missionPanel.add(actionPanel);

        involvementsTable.setModel(new InvolvementTableModel(bundle));
        jScrollPane1.setViewportView(involvementsTable);

        missionPanel.add(jScrollPane1);

        getContentPane().add(missionPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMissionButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelMissionButtonActionPerformed

    private void updateMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMissionButtonActionPerformed
        this.mission.setCode(missionPanel1.getMissionCode());
        this.mission.setLocation(missionPanel1.getMissionLocation());
        this.mission.setStart(missionPanel1.getMissionStart());
        this.mission.setEnd(missionPanel1.getMissionEnd());
        this.mission.setObjective(missionPanel1.getMissionObjective());
        this.mission.setOutcome(missionPanel1.getMissionOutcome());

        getMainWindow().updateMission(mission);
        close();
    }//GEN-LAST:event_updateMissionButtonActionPerformed

    private void removeMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMissionButtonActionPerformed
        getMainWindow().removeMission(mission);
        close();
    }//GEN-LAST:event_removeMissionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelMissionButton;
    private javax.swing.JTable involvementsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel missionPanel;
    private cz.muni.fi.pv168.agentmanager.app.gui.mission.MissionPanel missionPanel1;
    private javax.swing.JButton removeMissionButton;
    private javax.swing.JButton updateMissionButton;
    // End of variables declaration//GEN-END:variables

    private void setMission(Mission mission) {
        this.mission = mission;
        missionPanel1.setMission(mission);
    }

    private AgentManagerMain getMainWindow() {
        return (AgentManagerMain) getParent();
    }

    private void close() {
        this.dispose();
    }

}
