/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.agentmanager.app;

/**
 *
 * @author Jaromir Sys
 */
public class AgentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgentPanel
     */
    public AgentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        startPanel = new javax.swing.JPanel();
        bornLabel = new javax.swing.JLabel();
        bornSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        diedLabel = new javax.swing.JLabel();
        diedSpinner = new javax.swing.JSpinner();
        outcomePanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        levelSpinner = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        codePanel.setLayout(new java.awt.GridLayout());

        nameLabel.setText("Name");
        codePanel.add(nameLabel);

        nameTextField.setText("jTextField1");
        codePanel.add(nameTextField);

        add(codePanel);

        startPanel.setLayout(new java.awt.GridLayout());

        bornLabel.setText("Born");
        startPanel.add(bornLabel);

        bornSpinner.setModel(new javax.swing.SpinnerDateModel());
        bornSpinner.setToolTipText("");
        startPanel.add(bornSpinner);

        add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout());

        diedLabel.setText("Died");
        endPanel.add(diedLabel);

        diedSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(diedSpinner);

        add(endPanel);

        outcomePanel.setLayout(new java.awt.GridLayout());

        levelLabel.setText("Level");
        outcomePanel.add(levelLabel);

        levelSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        outcomePanel.add(levelSpinner);

        add(outcomePanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bornLabel;
    private javax.swing.JSpinner bornSpinner;
    private javax.swing.JPanel codePanel;
    private javax.swing.JLabel diedLabel;
    private javax.swing.JSpinner diedSpinner;
    private javax.swing.JPanel endPanel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JSpinner levelSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel outcomePanel;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
