package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Agent;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import cz.muni.fi.pv168.gmiterkosys.Mission;
import cz.muni.fi.pv168.gmiterkosys.Outcome;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * @author Jaromir Sys
 */
public class AgentManagerMain extends javax.swing.JFrame {

    /**
     * Creates new form AgentManagerMain
     */
    public AgentManagerMain() {
        initComponents();
        
        initMissionTable();
        initAgentTable();
        initInvolvementTable();
        
    }
    
    private void initMissionTable() {
        MissionTableModel missionTableModel = new MissionTableModel();
        missionTable.setModel(missionTableModel);
        ButtonRenderer br = new ButtonRenderer();
        missionTable.getColumn("Edit").setCellRenderer(br);
        missionTable.getColumn("Delete").setCellRenderer(br);
        
        // Test data
        Mission temp = getTestMission();
        missionTableModel.addMission(temp);
        missionTableModel.addMission(temp);
        missionTableModel.addMission(temp);
    }
    
    private void initAgentTable() {
        AgentTableModel agentTableModel = new AgentTableModel();
        agentTable.setModel(agentTableModel);
        ButtonRenderer br = new ButtonRenderer();
        agentTable.getColumn("Edit").setCellRenderer(br);
        agentTable.getColumn("Delete").setCellRenderer(br);
        
        // Test data
        Agent temp = getTestAgent();
        agentTableModel.addAgent(temp);
        agentTableModel.addAgent(temp);
        agentTableModel.addAgent(temp);
    }
        
    private void initInvolvementTable() {
        InvolvementTableModel involvementTableModel = new InvolvementTableModel();
        involvementTable.setModel(involvementTableModel);
        
        ButtonRenderer br = new ButtonRenderer();
        involvementTable.getColumn("Mission").setCellRenderer(br);
        involvementTable.getColumn("Agent").setCellRenderer(br);
        involvementTable.getColumn("Edit").setCellRenderer(br);
        involvementTable.getColumn("Delete").setCellRenderer(br);
        
        // Test data
        Involvement temp = getTestInvolvement();
        involvementTableModel.addInvolvement(temp);
        involvementTableModel.addInvolvement(temp);
        involvementTableModel.addInvolvement(temp);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Agents = new javax.swing.JPanel();
        createAgentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentTable = new javax.swing.JTable();
        Involvements = new javax.swing.JPanel();
        createInvolvementButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        involvementTable = new javax.swing.JTable();
        Missions = new javax.swing.JPanel();
        createMissionButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        missionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        Agents.setLayout(new java.awt.BorderLayout());

        createAgentButton.setText("Create Agent");
        Agents.add(createAgentButton, java.awt.BorderLayout.PAGE_START);

        agentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(agentTable);

        Agents.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Agents", Agents);

        Involvements.setLayout(new java.awt.BorderLayout());

        createInvolvementButton.setText("Create Involvement");
        Involvements.add(createInvolvementButton, java.awt.BorderLayout.PAGE_START);

        involvementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(involvementTable);

        Involvements.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Involvements", Involvements);

        Missions.setLayout(new java.awt.BorderLayout());

        createMissionButton.setText("Create Mission");
        Missions.add(createMissionButton, java.awt.BorderLayout.PAGE_START);

        missionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(missionTable);

        Missions.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Missions", Missions);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgentManagerMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agents;
    private javax.swing.JPanel Involvements;
    private javax.swing.JPanel Missions;
    private javax.swing.JTable agentTable;
    private javax.swing.JButton createAgentButton;
    private javax.swing.JButton createInvolvementButton;
    private javax.swing.JButton createMissionButton;
    private javax.swing.JTable involvementTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable missionTable;
    // End of variables declaration//GEN-END:variables

    private Mission getTestMission() {
        Mission temp = new Mission();
        
        temp.setCode("CODE");
        temp.setLocation("Location");
        temp.setStart(LocalDateTime.MAX);
        temp.setEnd(LocalDateTime.MIN);
        temp.setObjective("Objective");
        temp.setOutcome(Outcome.FAILED);
        
        return temp;
    }
    
    private Agent getTestAgent() {
        Agent temp = new Agent();
        
        temp.setName("Linda Fox");
        temp.setBorn(LocalDate.MIN);
        temp.setDied(LocalDate.MAX);
        temp.setLevel(6);
        
        return temp;
    }
    
    private Involvement getTestInvolvement() {
        Involvement temp = new Involvement();
        
        temp.setMission(getTestMission());
        temp.setAgent(getTestAgent());
        temp.setStart(LocalDateTime.MIN);
        temp.setEnd(LocalDateTime.MAX);
        
        return temp;
    }
}
