package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Agent;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import java.util.List;
import java.util.ResourceBundle;

/**
 *
 * @author Dominik Gmiterko
 */
public class AgentDetailDialog extends javax.swing.JDialog {
    
    private Agent agent;
    private List<Involvement> involvements;
    private ResultEnum result = ResultEnum.CANCEL;

    public ResultEnum getResult() {
        return result;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
        this.agentPanel1.setAgent(agent);
    }

    public void setInvolvements(List<Involvement> involvements) {
        this.involvements = involvements;
        for(Involvement i:involvements){
            ((InvolvementTableModel)this.involvementsTable.getModel()).addInvolvement(i);
        }
        
    }
    
    /**
     * Creates new form AgentDialog
     */
    public AgentDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentPanel = new javax.swing.JPanel();
        agentPanel1 = new cz.muni.fi.pv168.agentmanager.app.AgentPanel();
        actionPanel = new javax.swing.JPanel();
        updateAgentButton = new javax.swing.JButton();
        removeAgentButton = new javax.swing.JButton();
        cancelAgentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        involvementsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        agentPanel.setLayout(new javax.swing.BoxLayout(agentPanel, javax.swing.BoxLayout.Y_AXIS));
        agentPanel.add(agentPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        updateAgentButton.setText(bundle.getString("action.update")); // NOI18N
        updateAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(updateAgentButton);

        removeAgentButton.setText(bundle.getString("action.remove")); // NOI18N
        removeAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(removeAgentButton);

        cancelAgentButton.setText(bundle.getString("action.cancel")); // NOI18N
        cancelAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelAgentButton);

        agentPanel.add(actionPanel);

        involvementsTable.setModel(new InvolvementTableModel(bundle));
        jScrollPane1.setViewportView(involvementsTable);

        agentPanel.add(jScrollPane1);

        getContentPane().add(agentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAgentButtonActionPerformed
        this.result = ResultEnum.CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_cancelAgentButtonActionPerformed

    private void updateAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAgentButtonActionPerformed
        this.result = ResultEnum.UPDATE;
        this.agent.setName(agentPanel1.getAgentName());
        this.agent.setBorn(agentPanel1.getAgentBorn());
        this.agent.setDied(agentPanel1.getAgentDied());
        this.agent.setLevel(agentPanel1.getAgentLevel());
        this.setVisible(false);
    }//GEN-LAST:event_updateAgentButtonActionPerformed

    private void removeAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAgentButtonActionPerformed
        this.result = ResultEnum.REMOVE;
        this.setVisible(false);
    }//GEN-LAST:event_removeAgentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgentDetailDialog dialog = new AgentDetailDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel agentPanel;
    private cz.muni.fi.pv168.agentmanager.app.AgentPanel agentPanel1;
    private javax.swing.JButton cancelAgentButton;
    private javax.swing.JTable involvementsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeAgentButton;
    private javax.swing.JButton updateAgentButton;
    // End of variables declaration//GEN-END:variables
}
