package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Outcome;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dominik Gmiterko
 */
public class AgentDialog extends javax.swing.JDialog {

    /**
     * Creates new form AgentDialog
     */
    public AgentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentPanel = new javax.swing.JPanel();
        codePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        startPanel = new javax.swing.JPanel();
        bornLabel = new javax.swing.JLabel();
        bornSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        diedLabel = new javax.swing.JLabel();
        diedSpinner = new javax.swing.JSpinner();
        outcomePanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        levelSpinner = new javax.swing.JSpinner();
        actionPanel = new javax.swing.JPanel();
        createAgentButton = new javax.swing.JButton();
        cancelAgentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        agentPanel.setLayout(new javax.swing.BoxLayout(agentPanel, javax.swing.BoxLayout.Y_AXIS));

        codePanel.setLayout(new java.awt.GridLayout(1, 0));

        nameLabel.setText("Name");
        codePanel.add(nameLabel);

        nameTextField.setText("jTextField1");
        codePanel.add(nameTextField);

        agentPanel.add(codePanel);

        startPanel.setLayout(new java.awt.GridLayout(1, 0));

        bornLabel.setText("Born");
        startPanel.add(bornLabel);

        bornSpinner.setModel(new javax.swing.SpinnerDateModel());
        bornSpinner.setToolTipText("");
        startPanel.add(bornSpinner);

        agentPanel.add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout(1, 0));

        diedLabel.setText("Died");
        endPanel.add(diedLabel);

        diedSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(diedSpinner);

        agentPanel.add(endPanel);

        outcomePanel.setLayout(new java.awt.GridLayout(1, 0));

        levelLabel.setText("Level");
        outcomePanel.add(levelLabel);

        levelSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        outcomePanel.add(levelSpinner);

        agentPanel.add(outcomePanel);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        createAgentButton.setText("Create");
        actionPanel.add(createAgentButton);

        cancelAgentButton.setText("Cancel");
        cancelAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelAgentButton);

        agentPanel.add(actionPanel);

        getContentPane().add(agentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAgentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAgentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgentDialog dialog = new AgentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JLabel bornLabel;
    private javax.swing.JSpinner bornSpinner;
    private javax.swing.JButton cancelAgentButton;
    private javax.swing.JPanel codePanel;
    private javax.swing.JButton createAgentButton;
    private javax.swing.JLabel diedLabel;
    private javax.swing.JSpinner diedSpinner;
    private javax.swing.JPanel endPanel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JSpinner levelSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel outcomePanel;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
