/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.agentmanager.app;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author Jaromir Sys
 */
public class AgentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgentPanel
     */
    public AgentPanel() {
        initComponents();
    }
    
    public String getAgentName(){
        return nameTextField.getText();
    }
    
    public LocalDateTime getAgentBorn(){
        Date date = (Date)bornSpinner.getValue();
        return LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
    }
    
    public LocalDateTime getAgentDied(){
        Date date = (Date)diedSpinner.getValue();
        return LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
    }
    
    public int getAgentLevel(){
        return (int)levelSpinner.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        startPanel = new javax.swing.JPanel();
        bornLabel = new javax.swing.JLabel();
        bornSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        diedLabel = new javax.swing.JLabel();
        diedSpinner = new javax.swing.JSpinner();
        outcomePanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        levelSpinner = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        codePanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        nameLabel.setText(bundle.getString("agent.name")); // NOI18N
        codePanel.add(nameLabel);

        nameTextField.setText("jTextField1");
        codePanel.add(nameTextField);

        add(codePanel);

        startPanel.setLayout(new java.awt.GridLayout(1, 0));

        bornLabel.setText(bundle.getString("agent.born")); // NOI18N
        startPanel.add(bornLabel);

        bornSpinner.setModel(new javax.swing.SpinnerDateModel());
        bornSpinner.setToolTipText("");
        startPanel.add(bornSpinner);

        add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout(1, 0));

        diedLabel.setText(bundle.getString("agent.died")); // NOI18N
        endPanel.add(diedLabel);

        diedSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(diedSpinner);

        add(endPanel);

        outcomePanel.setLayout(new java.awt.GridLayout(1, 0));

        levelLabel.setText(bundle.getString("agent.level")); // NOI18N
        outcomePanel.add(levelLabel);

        levelSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        outcomePanel.add(levelSpinner);

        add(outcomePanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bornLabel;
    private javax.swing.JSpinner bornSpinner;
    private javax.swing.JPanel codePanel;
    private javax.swing.JLabel diedLabel;
    private javax.swing.JSpinner diedSpinner;
    private javax.swing.JPanel endPanel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JSpinner levelSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel outcomePanel;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
