package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.AgentManager;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import cz.muni.fi.pv168.gmiterkosys.InvolvementManager;
import cz.muni.fi.pv168.gmiterkosys.MissionManager;

/**
 *
 * @author Jaromir Sys
 */
public class InvolvementCreateDialog extends javax.swing.JDialog {

    private AgentManager agentManager;
    private MissionManager missionManager;
    private InvolvementManager involvementManager;
    
    /**
     * Creates new form InvolvementDialog
     */
    public InvolvementCreateDialog(java.awt.Frame parent, boolean modal,AgentManager agentManager,MissionManager missionManager,InvolvementManager involvementManager) {
        super(parent, modal);
        initComponents();
        AgentComboBoxModel agentComboBoxModel = new AgentComboBoxModel(agentManager.findAllAgents());
        MissionComboBoxModel missionComboBoxModel = new MissionComboBoxModel(missionManager.findAllMissions());
        involvementPanel1.setAgentComboBoxModel(agentComboBoxModel);
        involvementPanel1.setMissionComboBoxModel(missionComboBoxModel);
    }
    
    public InvolvementCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AgentComboBoxModel agentComboBoxModel = new AgentComboBoxModel(agentManager.findAllAgents());
        involvementPanel1.setAgentComboBoxModel(agentComboBoxModel);
    }

    public void setAgentManager(AgentManager agentManager) {
        this.agentManager = agentManager;
    }

    public void setMissionManager(MissionManager missionManager) {
        this.missionManager = missionManager;
    }

    public void setInvolvementManager(InvolvementManager involvementManager) {
        this.involvementManager = involvementManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        involvementPanel = new javax.swing.JPanel();
        involvementPanel1 = new cz.muni.fi.pv168.agentmanager.app.InvolvementPanel();
        actionPanel = new javax.swing.JPanel();
        createInvolvementButton = new javax.swing.JButton();
        cancelInvolvementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        involvementPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        involvementPanel.setLayout(new javax.swing.BoxLayout(involvementPanel, javax.swing.BoxLayout.PAGE_AXIS));
        involvementPanel.add(involvementPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        createInvolvementButton.setText("Create");
        createInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(createInvolvementButton);

        cancelInvolvementButton.setText("Cancel");
        cancelInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelInvolvementButton);

        involvementPanel.add(actionPanel);

        getContentPane().add(involvementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvolvementButtonActionPerformed
        Involvement involvement = new Involvement();
        involvement.setAgent(involvementPanel1.getInvolvementAgent());
        involvement.setMission(involvementPanel1.getInvolvementMission());
        involvement.setStart(involvementPanel1.getInvolvementStart());
        involvement.setEnd(involvementPanel1.getInvolvementEnd());
        involvementManager.createInvolvement(involvement);
        this.setVisible(false);
    }//GEN-LAST:event_createInvolvementButtonActionPerformed

    private void cancelInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInvolvementButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelInvolvementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvolvementCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvolvementCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvolvementCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvolvementCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvolvementCreateDialog dialog = new InvolvementCreateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelInvolvementButton;
    private javax.swing.JButton createInvolvementButton;
    private javax.swing.JPanel involvementPanel;
    private cz.muni.fi.pv168.agentmanager.app.InvolvementPanel involvementPanel1;
    // End of variables declaration//GEN-END:variables
}
