package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Agent;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import cz.muni.fi.pv168.gmiterkosys.Mission;
import java.util.List;

/**
 *
 * @author Jaromir Sys
 */
public class InvolvementDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form InvolvementDialog
     */
    
    private ResultEnum result = ResultEnum.CANCEL;
    private Involvement involvement;

    public ResultEnum getResult() {
        return result;
    }
    
    public void setInvolvement(Involvement involvement) {
        this.involvement = involvement;
        involvementPanel1.setInvolvement(involvement);
    }
    
    public InvolvementDetailDialog(java.awt.Frame parent, boolean modal,List<Agent> agents,List<Mission> missions) {
        super(parent, modal);
        initComponents();
        AgentComboBoxModel agentComboBoxModel = new AgentComboBoxModel(agents);
        MissionComboBoxModel missionComboBoxModel = new MissionComboBoxModel(missions);
        involvementPanel1.setAgentComboBoxModel(agentComboBoxModel);
        involvementPanel1.setMissionComboBoxModel(missionComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        involvementPanel = new javax.swing.JPanel();
        involvementPanel1 = new cz.muni.fi.pv168.agentmanager.app.InvolvementPanel();
        actionPanel = new javax.swing.JPanel();
        updateInvolvementButton = new javax.swing.JButton();
        removeInvolvementButton = new javax.swing.JButton();
        cancelInvolvementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        involvementPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        involvementPanel.setLayout(new javax.swing.BoxLayout(involvementPanel, javax.swing.BoxLayout.PAGE_AXIS));
        involvementPanel.add(involvementPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        updateInvolvementButton.setText(bundle.getString("action.update")); // NOI18N
        updateInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(updateInvolvementButton);

        removeInvolvementButton.setText(bundle.getString("action.remove")); // NOI18N
        removeInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(removeInvolvementButton);

        cancelInvolvementButton.setText(bundle.getString("action.cancel")); // NOI18N
        cancelInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelInvolvementButton);

        involvementPanel.add(actionPanel);

        getContentPane().add(involvementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInvolvementButtonActionPerformed
        involvement.setAgent(involvementPanel1.getInvolvementAgent());
        involvement.setMission(involvementPanel1.getInvolvementMission());
        involvement.setStart(involvementPanel1.getInvolvementStart());
        involvement.setEnd(involvementPanel1.getInvolvementEnd());
        result = ResultEnum.UPDATE;
        this.setVisible(false);
    }//GEN-LAST:event_updateInvolvementButtonActionPerformed

    private void removeInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInvolvementButtonActionPerformed
        result = ResultEnum.REMOVE;
        this.setVisible(false);
    }//GEN-LAST:event_removeInvolvementButtonActionPerformed

    private void cancelInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInvolvementButtonActionPerformed
        result = ResultEnum.CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_cancelInvolvementButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelInvolvementButton;
    private javax.swing.JPanel involvementPanel;
    private cz.muni.fi.pv168.agentmanager.app.InvolvementPanel involvementPanel1;
    private javax.swing.JButton removeInvolvementButton;
    private javax.swing.JButton updateInvolvementButton;
    // End of variables declaration//GEN-END:variables
}
