package cz.muni.fi.pv168.agentmanager.app;

/**
 *
 * @author Jaromir Sys
 */
public class InvolvementDialog extends javax.swing.JDialog {

    /**
     * Creates new form InvolvementDialog
     */
    public InvolvementDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        involvementPanel = new javax.swing.JPanel();
        agentPanel = new javax.swing.JPanel();
        agentLabel = new javax.swing.JLabel();
        agentComboBox = new javax.swing.JComboBox<String>();
        missionPanel = new javax.swing.JPanel();
        missionLabel = new javax.swing.JLabel();
        missionComboBox = new javax.swing.JComboBox<String>();
        startPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        startSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        endSpinner = new javax.swing.JSpinner();
        actionPanel = new javax.swing.JPanel();
        createInvolvementButton = new javax.swing.JButton();
        cancelInvolvementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        involvementPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        involvementPanel.setLayout(new javax.swing.BoxLayout(involvementPanel, javax.swing.BoxLayout.PAGE_AXIS));

        agentPanel.setLayout(new java.awt.GridLayout(1, 0));

        agentLabel.setText("Agent");
        agentPanel.add(agentLabel);

        agentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        agentPanel.add(agentComboBox);

        involvementPanel.add(agentPanel);

        missionPanel.setLayout(new java.awt.GridLayout(1, 0));

        missionLabel.setText("Mission");
        missionPanel.add(missionLabel);

        missionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        missionPanel.add(missionComboBox);

        involvementPanel.add(missionPanel);

        startPanel.setLayout(new java.awt.GridLayout(1, 0));

        startLabel.setText("Start");
        startPanel.add(startLabel);

        startSpinner.setModel(new javax.swing.SpinnerDateModel());
        startPanel.add(startSpinner);

        involvementPanel.add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout(1, 0));

        endLabel.setText("End");
        endPanel.add(endLabel);

        endSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(endSpinner);

        involvementPanel.add(endPanel);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        createInvolvementButton.setText("Create");
        createInvolvementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvolvementButtonActionPerformed(evt);
            }
        });
        actionPanel.add(createInvolvementButton);

        cancelInvolvementButton.setText("Cancel");
        actionPanel.add(cancelInvolvementButton);

        involvementPanel.add(actionPanel);

        getContentPane().add(involvementPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvolvementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvolvementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createInvolvementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvolvementDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvolvementDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvolvementDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvolvementDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvolvementDialog dialog = new InvolvementDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JComboBox<String> agentComboBox;
    private javax.swing.JLabel agentLabel;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JButton cancelInvolvementButton;
    private javax.swing.JButton createInvolvementButton;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel endPanel;
    private javax.swing.JSpinner endSpinner;
    private javax.swing.JPanel involvementPanel;
    private javax.swing.JComboBox<String> missionComboBox;
    private javax.swing.JLabel missionLabel;
    private javax.swing.JPanel missionPanel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JSpinner startSpinner;
    // End of variables declaration//GEN-END:variables
}
