/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Agent;
import cz.muni.fi.pv168.gmiterkosys.Involvement;
import cz.muni.fi.pv168.gmiterkosys.Mission;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Jaromir Sys
 */
public class InvolvementPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvolvementPanel
     */
    public InvolvementPanel() {
        initComponents();
    }
    
    public Agent getInvolvementAgent(){
        return (Agent)agentComboBox.getSelectedItem();
    }
    
    public Mission getInvolvementMission(){
        return (Mission)missionComboBox.getSelectedItem();
    }
    
    public LocalDateTime getInvolvementStart(){
        Date date = (Date)startSpinner.getValue();
        return LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
    }
    
    public LocalDateTime getInvolvementEnd(){
        Date date = (Date)endSpinner.getValue();
        return LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
    }
    
    public void setAgentComboBoxModel(ComboBoxModel cbm){
        agentComboBox.setModel(cbm);
    }
    
    public void setMissionComboBoxModel(ComboBoxModel cbm){
        missionComboBox.setModel(cbm);
    }
    
    public void setInvolvement(Involvement involvement) {
        missionComboBox.setSelectedItem(involvement.getMission());
        agentComboBox.setSelectedItem(involvement.getAgent());
        startSpinner.setValue(Date.from(involvement.getStart().atZone(ZoneId.systemDefault()).toInstant()));
        endSpinner.setValue(Date.from(involvement.getEnd().atZone(ZoneId.systemDefault()).toInstant()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentPanel = new javax.swing.JPanel();
        agentLabel = new javax.swing.JLabel();
        agentComboBox = new javax.swing.JComboBox<>();
        missionPanel = new javax.swing.JPanel();
        missionLabel = new javax.swing.JLabel();
        missionComboBox = new javax.swing.JComboBox<>();
        startPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        startSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        endSpinner = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        agentPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        agentLabel.setText(bundle.getString("involvement.agent")); // NOI18N
        agentPanel.add(agentLabel);

        agentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        agentPanel.add(agentComboBox);

        add(agentPanel);

        missionPanel.setLayout(new java.awt.GridLayout(1, 0));

        missionLabel.setText(bundle.getString("involvement.mission")); // NOI18N
        missionPanel.add(missionLabel);

        missionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        missionPanel.add(missionComboBox);

        add(missionPanel);

        startPanel.setLayout(new java.awt.GridLayout(1, 0));

        startLabel.setText(bundle.getString("involvement.start")); // NOI18N
        startPanel.add(startLabel);

        startSpinner.setModel(new javax.swing.SpinnerDateModel());
        startPanel.add(startSpinner);

        add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout(1, 0));

        endLabel.setText(bundle.getString("involvement.end")); // NOI18N
        endPanel.add(endLabel);

        endSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(endSpinner);

        add(endPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agentComboBox;
    private javax.swing.JLabel agentLabel;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel endPanel;
    private javax.swing.JSpinner endSpinner;
    private javax.swing.JComboBox<String> missionComboBox;
    private javax.swing.JLabel missionLabel;
    private javax.swing.JPanel missionPanel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JSpinner startSpinner;
    // End of variables declaration//GEN-END:variables
}
