package cz.muni.fi.pv168.agentmanager.app;

import cz.muni.fi.pv168.gmiterkosys.Outcome;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jaromir Sys
 */
public class MissionDialog extends javax.swing.JDialog {

    /**
     * Creates new form MissionDialog
     */
    public MissionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        outcomeComboBox.setModel(new DefaultComboBoxModel(Outcome.values()));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        missionPanel = new javax.swing.JPanel();
        codePanel = new javax.swing.JPanel();
        codeLabel = new javax.swing.JLabel();
        codeTextField = new javax.swing.JTextField();
        locationPanel = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        startPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        startSpinner = new javax.swing.JSpinner();
        endPanel = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        endSpinner = new javax.swing.JSpinner();
        objectivePanel = new javax.swing.JPanel();
        objectiveLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        objectiveTextArea = new javax.swing.JTextArea();
        outcomePanel = new javax.swing.JPanel();
        outcomeLabel = new javax.swing.JLabel();
        outcomeComboBox = new javax.swing.JComboBox<String>();
        actionPanel = new javax.swing.JPanel();
        createMissionButton = new javax.swing.JButton();
        cancelMissionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        missionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        missionPanel.setLayout(new javax.swing.BoxLayout(missionPanel, javax.swing.BoxLayout.Y_AXIS));

        codePanel.setLayout(new java.awt.GridLayout(1, 0));

        codeLabel.setText("Code");
        codePanel.add(codeLabel);

        codeTextField.setText("jTextField1");
        codePanel.add(codeTextField);

        missionPanel.add(codePanel);

        locationPanel.setLayout(new java.awt.GridLayout(1, 0));

        locationLabel.setText("Location");
        locationPanel.add(locationLabel);

        locationTextField.setText("jTextField2");
        locationPanel.add(locationTextField);

        missionPanel.add(locationPanel);

        startPanel.setLayout(new java.awt.GridLayout(1, 0));

        startLabel.setText("Start");
        startPanel.add(startLabel);

        startSpinner.setModel(new javax.swing.SpinnerDateModel());
        startSpinner.setToolTipText("");
        startPanel.add(startSpinner);

        missionPanel.add(startPanel);

        endPanel.setLayout(new java.awt.GridLayout(1, 0));

        endLabel.setText("End");
        endPanel.add(endLabel);

        endSpinner.setModel(new javax.swing.SpinnerDateModel());
        endPanel.add(endSpinner);

        missionPanel.add(endPanel);

        objectivePanel.setLayout(new java.awt.GridLayout(1, 0));

        objectiveLabel.setText("Objective");
        objectivePanel.add(objectiveLabel);

        objectiveTextArea.setColumns(20);
        objectiveTextArea.setRows(5);
        jScrollPane1.setViewportView(objectiveTextArea);

        objectivePanel.add(jScrollPane1);

        missionPanel.add(objectivePanel);

        outcomePanel.setLayout(new java.awt.GridLayout(1, 0));

        outcomeLabel.setText("Outcome");
        outcomePanel.add(outcomeLabel);
        outcomePanel.add(outcomeComboBox);

        missionPanel.add(outcomePanel);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        createMissionButton.setText("Create");
        actionPanel.add(createMissionButton);

        cancelMissionButton.setText("Cancel");
        cancelMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMissionButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelMissionButton);

        missionPanel.add(actionPanel);

        getContentPane().add(missionPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMissionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMissionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MissionDialog dialog = new MissionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelMissionButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JPanel codePanel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JButton createMissionButton;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel endPanel;
    private javax.swing.JSpinner endSpinner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel locationPanel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JPanel missionPanel;
    private javax.swing.JLabel objectiveLabel;
    private javax.swing.JPanel objectivePanel;
    private javax.swing.JTextArea objectiveTextArea;
    private javax.swing.JComboBox<String> outcomeComboBox;
    private javax.swing.JLabel outcomeLabel;
    private javax.swing.JPanel outcomePanel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JSpinner startSpinner;
    // End of variables declaration//GEN-END:variables
}
