package cz.muni.fi.pv168.agentmanager.app.gui.agent;

import cz.muni.fi.pv168.agentmanager.app.gui.AgentManagerMain;
import cz.muni.fi.pv168.agentmanager.app.gui.involvement.InvolvementTableModel;
import cz.muni.fi.pv168.agentmanager.app.workers.involvement.InvolvementByAgentTableModelWorker;
import cz.muni.fi.pv168.gmiterkosys.Agent;
import cz.muni.fi.pv168.gmiterkosys.InvolvementManager;

/**
 *
 * @author Dominik Gmiterko
 */
public class AgentDetailDialog extends javax.swing.JDialog {

    private Agent agent;

    /**
     * Creates new form AgentDialog
     *
     * @param parent
     * @param agent
     * @param involvementManager
     */
    public AgentDetailDialog(java.awt.Frame parent, Agent agent, InvolvementManager involvementManager) {
        super(parent, false);
        initComponents();
        setAgent(agent);

        //load data
        new InvolvementByAgentTableModelWorker(agent, involvementManager, ((InvolvementTableModel) involvementsTable.getModel())).execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentPanel = new javax.swing.JPanel();
        agentPanel1 = new cz.muni.fi.pv168.agentmanager.app.gui.agent.AgentPanel();
        actionPanel = new javax.swing.JPanel();
        updateAgentButton = new javax.swing.JButton();
        removeAgentButton = new javax.swing.JButton();
        cancelAgentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        involvementsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        agentPanel.setLayout(new javax.swing.BoxLayout(agentPanel, javax.swing.BoxLayout.Y_AXIS));
        agentPanel.add(agentPanel1);

        actionPanel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/pv168/agentmanager/app/Texts"); // NOI18N
        updateAgentButton.setText(bundle.getString("action.update")); // NOI18N
        updateAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(updateAgentButton);

        removeAgentButton.setText(bundle.getString("action.remove")); // NOI18N
        removeAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(removeAgentButton);

        cancelAgentButton.setText(bundle.getString("action.cancel")); // NOI18N
        cancelAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAgentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelAgentButton);

        agentPanel.add(actionPanel);

        involvementsTable.setModel(new InvolvementTableModel(bundle));
        jScrollPane1.setViewportView(involvementsTable);

        agentPanel.add(jScrollPane1);

        getContentPane().add(agentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAgentButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelAgentButtonActionPerformed

    private void updateAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAgentButtonActionPerformed
        agent.setName(agentPanel1.getAgentName());
        agent.setBorn(agentPanel1.getAgentBorn());
        agent.setDied(agentPanel1.getAgentDied());
        agent.setLevel(agentPanel1.getAgentLevel());

        getMainWindow().updateAgent(agent);
        close();
    }//GEN-LAST:event_updateAgentButtonActionPerformed

    private void removeAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAgentButtonActionPerformed
        getMainWindow().removeAgent(agent);
        close();
    }//GEN-LAST:event_removeAgentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel agentPanel;
    private cz.muni.fi.pv168.agentmanager.app.gui.agent.AgentPanel agentPanel1;
    private javax.swing.JButton cancelAgentButton;
    private javax.swing.JTable involvementsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeAgentButton;
    private javax.swing.JButton updateAgentButton;
    // End of variables declaration//GEN-END:variables

    private void setAgent(Agent agent) {
        this.agent = agent;
        agentPanel1.setAgent(agent);
    }

    private AgentManagerMain getMainWindow() {
        return (AgentManagerMain) getParent();
    }

    private void close() {
        this.dispose();
    }

}
